# Generated by Django 4.2.16 on 2024-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderproduct_remove_order_customer_remove_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'In delivery'), (1, 'Done')], default=0, max_length=20),
        ),
    ]
