# Generated by Django 4.2.16 on 2024-10-22 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
