# Generated by Django 4.2.16 on 2024-10-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_orderproduct_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_uuid',
            field=models.UUIDField(),
        ),
    ]
