# Generated by Django 4.2.16 on 2024-10-22 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orderproduct_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
