# Generated by Django 4.2.16 on 2024-10-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderproduct_product_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
